### PR TITLE
Build scripts updates (for third party libraries and programs)

### PR DESCRIPTION
**Pull request by pvelissariou1**
The build scripts have been updated to allow configuring the third party libraries and programs:
a) using environment variables that point to the location of the pre-compiled (externally or internally to CoastalApp)
    libraries and programs (CoastalApp exports relevant environment variables that are passed to the modeling components)
b) compiling the libraries within CoastalApp per user's request using the --thirdparty option to the build script.

Currently only DateTime and ParMetis are supported. CoastalApp does not ship with ParMetis and it is
the user's responsibility to download the library (the script scripts/download_parmetis.sh can be used for that purpose).

### CODE REVIEW

**Comment by saeed-moghimi-noaa** [comment]
Looks good

**Review by saeed-moghimi-noaa — COMMENTED** [review]
Looks good in general.

**Comment by pvelissariou1** [comment]
Thanks,

Tested with SCHISM and partially with WW3 (gfortran). It seems to be
working well
and at the same time we are avoiding licensing issues. The code is 100%
modularized
in that aspect.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
I am reopening this PR

**Comment by saeed-moghimi-noaa** [comment]
Saeed Moghimi - NOAA Federal, Now
It says, 
ci/circleci: Build Error
  

      

    —
      Your tests failed on CircleCI
Do we want to ignore this?

Panagiotis Velissariou - NOAA Affiliate, Now
yes

**Review by saeed-moghimi-noaa — APPROVED** [review]

**Review by saeed-moghimi-noaa — APPROVED** [review]

**Comment by platipodium** [comment]
Sorry, I cannot figure out how to properly set METISHOME.  

- env variables are *not* honored

**Comment by pvelissariou1** [comment]
Hi Carsten,

You may run the build script as:
PARMETISHOME=location_of_installed_parmetis build.sh options...
The script exports the variables PARMETISHOME, METISHOME, METIS and
METIS_PATH
to all modeling components.

If you want to compile ParMetis within CoastalApp, run the script:
scripts/download_parametis.sh to download parmetis into the thirdparty_open
directory, then
run the build.sh script as:
"build.sh options... -tp parmetis" to first build parmetis and then build
the model component.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by saeed-moghimi-noaa** [comment]
Takis,

If SCHISM or FVCOM already includes Parmatis, the only thing WW3 needed is
to have the ability to find the exported location of the installed folder.
I am still not convinced that we need a new Parmatis installation within
CoastalApp ...

-Saeed
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by platipodium** [comment]
I guess we need to separate the issues:

1. Dealing with an externally provided library as favoured by @saeed-moghimi-noaa and @platipodium
2. As a fallback downloading and installing these libraries to third_party with the helper scripts provided by @pvelissariou1  

Let's concentrate here on (1.)

**Comment by platipodium** [comment]
Thanks @pvelissariou1, I got #127 to work now and can confirm (1.) working.  

I am still stuck on (2.), as the `compiler` options is not honoured, see #128

**Comment by pvelissariou1** [comment]
Saeed,

It is up to the user to compile parmetis within CoastalApp or not. He/She
can set the
PARMETISHOME env. variable variable before running build.sh to point
to an already compiled parmetis external to CostalApp or internal to
Coastal App (like in SCHISM)
and in this case all models can use the same library.
So all options are covered no matter what, and no matter the platform used.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Pull request merged**
