### PR TITLE
add PaHM to build scripts and submodules

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**
blocked by https://github.com/noaa-ocs-modeling/NEMS/pull/7

### CODE REVIEW

**Review by pvelissariou1 — APPROVED** [review]

**Comment by zacharyburnettNOAA** [comment]
still some conflicts in the following files:
```
modulefiles/envmodules_intel.orion.orig
scripts/build.sh 
```

**Comment by zacharyburnettNOAA** [comment]
```
build.sh: line 273: compileNems: command not found
```

**Comment by zacharyburnettNOAA** [comment]
I was able to

**Comment by zacharyburnettNOAA** [comment]
```
 Zachary.Burnett@hfe11  sandy-atmesh-adcirc/spinup
 > ls -l
total 5088
-rw-r--r-- 1 Zachary.Burnett coastal     715 Jun 29 20:16 ADCIRC_COLDSTART_SPINUP.err.log
-rw-r--r-- 1 Zachary.Burnett coastal 1400171 Jun 29 20:16 ADCIRC_COLDSTART_SPINUP.out.log
-rw-r--r-- 1 Zachary.Burnett coastal       0 Jun 29 20:14 ADCIRC_SETUP_SPINUP.err.log
-rw-r--r-- 1 Zachary.Burnett coastal    7259 Jun 29 20:14 ADCIRC_SETUP_SPINUP.out.log
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0000
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0001
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0002
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0003
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0004
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0005
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0006
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0007
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0008
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0009
drwxr-sr-x 2 Zachary.Burnett coastal    4096 Jun 29 20:14 PE0010
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET00.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET01.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET02.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET03.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET04.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET05.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET06.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET07.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET08.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET09.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal  183003 Jun 29 20:16 PET10.ESMF_LogFile
-rw-r--r-- 1 Zachary.Burnett coastal     352 Jun 29 20:14 adcirc.job
lrwxrwxrwx 1 Zachary.Burnett coastal      15 Jun 29 20:14 atm_namelist.rc -> model_configure
-rw-r--r-- 1 Zachary.Burnett coastal      45 Jun 29 20:14 config.rc
-rw-r--r-- 1 Zachary.Burnett coastal   10600 Jun 29 20:14 fort.13
lrwxrwxrwx 1 Zachary.Burnett coastal      10 Jun 29 20:14 fort.14 -> ../fort.14
-rw-r--r-- 1 Zachary.Burnett coastal    7458 Jun 29 20:14 fort.15
-rw-r--r-- 1 Zachary.Burnett coastal    1258 Jun 29 20:14 fort.16
-rw-r--r-- 1 Zachary.Burnett coastal  242178 Jun 29 20:16 fort.63.nc
-rw-r--r-- 1 Zachary.Burnett coastal  129351 Jun 29 20:14 fort.64.nc
-rw-r--r-- 1 Zachary.Burnett coastal  164870 Jun 29 20:16 fort.67.nc
-rw-r--r-- 1 Zachary.Burnett coastal  138581 Jun 29 20:14 fort.68.nc
-rw-r--r-- 1 Zachary.Burnett coastal  223619 Jun 29 20:14 fort.80
-rw-r--r-- 1 Zachary.Burnett coastal  135266 Jun 29 20:16 maxele.63.nc
-rw-r--r-- 1 Zachary.Burnett coastal  140044 Jun 29 20:16 maxvel.63.nc
-rw-r--r-- 1 Zachary.Burnett coastal  387771 Jun 29 20:14 metis_graph.txt
-rw-r--r-- 1 Zachary.Burnett coastal     437 Jun 29 20:14 model_configure
-rw-r--r-- 1 Zachary.Burnett coastal     298 Jun 29 20:14 nems.configure
-rw-r--r-- 1 Zachary.Burnett coastal   39910 Jun 29 20:14 partmesh.txt
-rw-r--r-- 1 Zachary.Burnett coastal     386 Jun 29 20:14 setup.job
```

**Comment by zacharyburnettNOAA** [comment]
HOWEVER, the hotstart run failed with the following error in `runs/unperturbed/ADCIRC_SETUP_unperturbed.err.log`
```
forrtl: severe (59): list-directed I/O syntax error, unit 15, file /scratch2/COASTAL/coastal/save/shared/working/takis/shinnecock-pahm-tests-hera/sandy-atmesh-adcirc/runs/unperturbed/fort.15
Image              PC                Routine            Line        Source
adcprep            0000000000697ECE  Unknown               Unknown  Unknown
adcprep            00000000006CEC60  Unknown               Unknown  Unknown
adcprep            000000000040F1A6  presizes_mp_sizeu        1257  presizes.F
adcprep            000000000042D06F  prepinput_                436  adcprep.F
adcprep            000000000042BB2B  MAIN__                    239  adcprep.F
adcprep            000000000040B65E  Unknown               Unknown  Unknown
libc-2.17.so       00002ABA62FBB555  __libc_start_main     Unknown  Unknown
adcprep            000000000040B569  Unknown               Unknown  Unknown
srun: error: h6c55: task 0: Exited with exit code 59
srun: launch/slurm: _step_signal: Terminating StepId=20249063.1
```

**Comment by zacharyburnettNOAA** [comment]
moving run errors to https://github.com/noaa-ocs-modeling/CoupledModelDriver/issues/108

**Comment by zacharyburnettNOAA** [comment]
merged this branch into `feature/schism` with d2e0a24

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 @zacharyburnettNOAA   Is this issue completed? Please close if it is.

**Comment by zacharyburnettNOAA** [comment]
> @pvelissariou1 @zacharyburnettNOAA Is this issue completed? Please close if it is.

we are still working on this but will close it when we finish

**Comment by zacharyburnettNOAA** [comment]
CoastalApp priorities:
1. merge branch to `main`
2. incorporate latest version of WaveWatch III into CoastalApp
3. upgrade NUOPC / NEMS system
4. include CDAPS - include HYCOM in ADCIRC

@pvelissariou1

**Pull request merged**
