### PR TITLE
add SCHISM submodule and build files

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**
these changes were manually ported over from https://github.com/pvelissariou1/ADC-WW3-NWM-SCHISM-NEMS/, with commits amended to show authorship to @pvelissariou1 and @platipodium under the email addresses used in the commits

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
continuation of #43 , but this one is actually merging into `master`

**Review by pvelissariou1 — APPROVED** [review]

**Comment by zacharyburnettNOAA** [comment]
still doing some testing so don't merge just yet

**Review by zacharyburnettNOAA — COMMENTED** [review]
need to fix submodules; the commits to `NEMS`, `SCHISM`, and `schism-esmf` were not pushed, so I need to recreate them

**Comment by zacharyburnettNOAA** [comment]
waiting on https://github.com/schism-dev/schism/pull/31

**Comment by zacharyburnettNOAA** [comment]
pushed commits to submodules, updated submodule pointer to correct commit head

testing build now

**Comment by zacharyburnettNOAA** [comment]
@platipodium I've merged `feature/pahm` into `feature/schism`, which included @pvelissariou1's updates to the build system but also the PaHM submodule

Let me know if there are any glaring problems, as I can always revert d2e0a24

**Comment by platipodium** [comment]
looking good so far!

**Comment by zacharyburnettNOAA** [comment]
added a github workflow that validates submodule pointers

**Pull request merged**
